const exportStyle = `
<style>
body {
    margin: 0;
    padding: 24px;
    background: #f3f4f6;
    font-family: Consolas, Monaco, monospace;
}
#exportWrapper {
    max-width: 1200px;
    margin: auto;
    background: #ffffff;
    padding: 24px;
}
pre {
    background: #f9fafb;
    border: 1px solid #e5e7eb;
    padding: 12px;
    white-space: pre-wrap;
}
.added {
    background: #dcfce7;
    color: #166534;
}
.removed {
    background: #fee2e2;
    color: #991b1b;
    text-decoration: line-through;
}
table { border-collapse: collapse; width: 100%; font-size: 13px; }
table td, table th { border: 1px solid #e2e4e8; padding: 6px 10px; }
table .diff-cell { background: #fee2e2; color: #991b1b; }
table caption { font-weight: 600; margin-bottom: 8px; color: #1a1a2e; }
img { max-width: 100%; border: 1px solid #e2e4e8; border-radius: 8px; }
</style>
`;

function downloadHTML() {
    const mode = window.currentMode || 'text';
    const timestamp = new Date().toLocaleString();

    if (mode === 'image') {
        const canvasA = document.getElementById('canvasA');
        const canvasB = document.getElementById('canvasB');
        const canvasDiff = document.getElementById('canvasDiff');

        if (!canvasA.width || !canvasB.width) {
            alert('No image comparison to export.');
            return;
        }

        const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Image Compare Result</title>
    <style>
        body { margin: 0; padding: 24px; background: #f3f4f6; font-family: sans-serif; }
        h1 { margin: 0 0 8px; font-size: 24px; }
        .subtitle { color: #666; font-size: 14px; margin-bottom: 20px; }
        .canvas-row { display: flex; gap: 16px; margin-bottom: 20px; align-items: flex-start; }
        .canvas-item { flex: 1; }
        .canvas-item h3 { margin: 0 0 8px; font-size: 14px; color: #333; }
        .canvas-item img { max-width: 100%; border: 1px solid #e2e4e8; border-radius: 8px; }
    </style>
</head>
<body>
    <h1>Image Compare Result</h1>
    <div class="subtitle">Generated by https://textcompare.top &middot; ${timestamp}</div>
    <div class="canvas-row">
        <div class="canvas-item">
            <h3>Image A</h3>
            <img src="${canvasA.toDataURL('image/png')}" alt="Image A">
        </div>
        <div class="canvas-item">
            <h3>Image B</h3>
            <img src="${canvasB.toDataURL('image/png')}" alt="Image B">
        </div>
        <div class="canvas-item">
            <h3>Differences</h3>
            <img src="${canvasDiff.toDataURL('image/png')}" alt="Differences">
        </div>
    </div>
</body>
</html>`;

        const blob = new Blob([html], { type: "text/html;charset=utf-8" });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = "image-compare-result.html";
        link.click();
        URL.revokeObjectURL(link.href);
        return;
    }

    const baseText = document.getElementById("baseText").value;
    const newText = document.getElementById("newText").value;
    const resultHtml = document.getElementById("outputdiv").innerHTML;

    const hasContent = (baseText || newText || resultHtml.trim());
    if (!hasContent) {
        alert("No content to export.");
        return;
    }

    document.getElementById("exportBase").innerText = baseText;
    document.getElementById("exportNew").innerText = newText;
    document.getElementById("exportResult").innerHTML = resultHtml;
    document.getElementById("exportTime").innerText = timestamp;

    const wrapper = document.getElementById("exportWrapper");
    wrapper.style.cssText = "";

    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Text Compare Result</title>
${exportStyle}
</head>
<body>
${wrapper.outerHTML}
</body>
</html>`.trim();

    const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = "text-compare-result.html";
    link.click();
    URL.revokeObjectURL(link.href);
}